# JVM args for the Gradle daemon. 4G is comfortable for AGP + R8.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX / Kotlin
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Build performance
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=false
